server:
  port: 8888
spring:
  application:
    name: WsMessageSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wang147896321.
    url: jdbc:mysql://47.108.139.22:3306/WsMS?serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mappers/*xml